export const RECEIVE_GET_STATION = 'RECEIVE_GET_STATION'
export const REQUEST_GET_STATION = 'REQUEST_GET_STATION'

export const RECEIVE_GET_VALUE_DETAILS = 'RECEIVE_GET_VALUE_DETAILS'
export const REQUEST_GET_VALUE_DETAILS = 'REQUEST_GET_VALUE_DETAILS'


export const REQUEST_POST_VALUE_SEARCH = 'REQUEST_POST_VALUE_SEARCH' //搜索未完成
export const RECEIVE_POST_VALUE_SEARCH = 'RECEIVE_POST_VALUE_SEARCH' //搜索已完成
